global using Lintellect.Api.Application.Common.Interfaces;
global using Lintellect.Api.Domain.Entities;
global using Lintellect.Api.Domain.Enums;
global using Lintellect.Api.Domain.Events;
global using Lintellect.Api.UnitTests.Builders;
global using Lintellect.Shared.Models;
global using Mediator;
global using NSubstitute;
global using NUnit.Framework;
