// <auto-generated />
using System;
using System.Text.Json;
using Lintellect.Api.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Lintellect.Api.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260710104813_ReanalysisCommitTracking")]
    partial class ReanalysisCommitTracking
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Lintellect.Api.Domain.Entities.AnalysisJob", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AnalyzerUsed")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<string>("DetailedAnalysis")
                        .HasColumnType("text");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<int?>("InitialCommentThreadId")
                        .HasColumnType("integer");

                    b.Property<string>("InlineSuggestions")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("LastModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("text");

                    b.Property<string>("ReanalysisBaseCommitId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("SourceCommitId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset?>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Summary")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Created");

                    b.HasIndex("Status");

                    b.ToTable("AnalysisJobs");
                });

            modelBuilder.Entity("Lintellect.Api.Domain.Entities.WebhookEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text");

                    b.Property<JsonDocument>("EventPayload")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<int>("EventType")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("LastModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("ProcessedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Provider")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("ReceivedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("WebhookEvents");
                });

            modelBuilder.Entity("Lintellect.Api.Domain.Entities.AnalysisJob", b =>
                {
                    b.OwnsOne("Lintellect.Shared.Models.AnalysisRequest", "AnalysisRequest", b1 =>
                        {
                            b1.Property<Guid>("AnalysisJobId");

                            b1.Property<bool>("EnableAzureDevopsCodeOwners");

                            b1.Property<bool>("EnableDescriptionSummary");

                            b1.Property<bool>("EnableInitialComment");

                            b1.Property<bool>("EnableInlineSuggestions");

                            b1.Property<bool>("EnableSummaryComment");

                            b1.Property<bool>("EnableWorkItemContext");

                            b1.PrimitiveCollection<string>("FileExclusions")
                                .IsRequired();

                            b1.Property<int>("GitProvider");

                            b1.Property<int>("Language");

                            b1.PrimitiveCollection<string>("McpServer")
                                .IsRequired();

                            b1.HasKey("AnalysisJobId");

                            b1.ToTable("AnalysisJobs");

                            b1
                                .ToJson("AnalysisRequest")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("AnalysisJobId");

                            b1.OwnsOne("Lintellect.Shared.Models.GitInfo", "GitInfo", b2 =>
                                {
                                    b2.Property<Guid>("AnalysisRequestAnalysisJobId");

                                    b2.Property<string>("CommitId")
                                        .IsRequired();

                                    b2.Property<string>("ProjectName");

                                    b2.Property<int>("PullRequestId");

                                    b2.Property<string>("RepositoryName")
                                        .IsRequired();

                                    b2.Property<int>("Type");

                                    b2.HasKey("AnalysisRequestAnalysisJobId");

                                    b2.ToTable("AnalysisJobs");

                                    b2.WithOwner()
                                        .HasForeignKey("AnalysisRequestAnalysisJobId");
                                });

                            b1.Navigation("GitInfo");
                        });

                    b.Navigation("AnalysisRequest");
                });
#pragma warning restore 612, 618
        }
    }
}
